# Updates with ruRU localization if needed (utf8 encoding!)

set character set utf8;

-- .achievement status
REPLACE INTO `trinity_string` VALUES ('820','Achievement entry %u is not found!',null,null,null,null,null,null,null,'Достижение ID %u не существует!');
REPLACE INTO `trinity_string` VALUES ('821','Achievement %u progress for player %s:',null,null,null,null,null,null,null,'Достижение %u для игрока %s:');
REPLACE INTO `trinity_string` VALUES ('822','Criteria %u : %s.',null,null,null,null,null,null,null,'Критерий %u : %s.');
REPLACE INTO `command` VALUES ('achievement status','3','Syntax: .achievement status $achEntry [$player]\n\rShow status of each criteria of $achEntry achievement for $player or targeted player.\r\nTarget player should be online.');

-- a finer control of GM levels
UPDATE `command` SET `security` = 8 WHERE `name` IN (
 'account create',
 'account delete',
 'account onlinelist',
 'account set gmlevel',
 'account set password',
 'character erase',
 'character deleted delete',
 'character deleted old',
 'server togglequerylog');
UPDATE `command` SET `security` = 7 WHERE `name` IN (
 'account set',
 'bank',
 'guild delete',
 'pdump load',
 'server set closed',
 'character deleted list',
 'character deleted restore');
UPDATE `command` SET `security` = 6 WHERE `name` IN (
 'achievement',
 'achievement add',
 'aura',
 'ban ip',
 'banlist',
 'bindsight',
 'cast',
 'channel set ownership',
 'character changefaction',
 'character changerace',
 'character rename',
 'cometome',
 'damage',
 'debug',
 'distance',
 'flusharenapoints',
 'gm list',
 'gobject add',
 'gobject delete',
 'gobject set state',
 'guild',
 'guild create',
 'guild invite',
 'guild rank',
 'guild uninvite',
 'hidearea',
 'honor add',
 'honor add kill',
 'honor update',
 'instance savedata',
 'itemmove',
 'learn all',
 'linkgrave',
 'list auras',
 'list creature',
 'list item',
 'list object',
 'lookup area',
 'lookup creature',
 'lookup object',
 'modify arena',
 'modify bit',
 'modify faction',
 'modify gender',
 'modify spell',
 'modify tp',
 'movegens',
 'neargrave',
 'npc add',
 'npc add formation',
 'npc add item',
 'npc add move',
 'npc delete item',
 'npc follow',
 'npc follow stop',
 'npc move',
 'npc set allowmove',
 'npc set entry',
 'npc set factionid',
 'npc set flag',
 'npc set link',
 'npc set model',
 'npc set movetype',
 'npc set phase',
 'npc set spawndist',
 'pdump',
 'pdump write',
 'pet create',
 'pet learn',
 'possess',
 'reload',
 'saveall',
 'send items',
 'send message',
 'send money',
 'server',
 'server idlerestart',
 'server idlerestart cancel',
 'server idleshutdown',
 'server idleshutdown cancel',
 'server restart',
 'server restart cancel',
 'server shutdown',
 'server shutdown cancel',
 'showarea',
 'tele add',
 'tele del',
 'ticket delete',
 'unbindsight',
 'unpossess',
 'wg',
 'wp reload');
UPDATE `command` SET `security` = 6 WHERE `name` LIKE 'debug %'
 OR `name` LIKE 'reload %' OR `name` LIKE 'cast %'OR `name` LIKE 'learn all %'
 OR `name` LIKE 'reset %' OR `name` LIKE 'wg %';
UPDATE `command` SET `security` = 7 where `name` = 'reload config';
UPDATE `command` SET `security` = 5 WHERE `name` IN (
 'additemset',
 'ban',
 'ban account',
 'ban playeraccount',
 'banlist',
 'banlist account',
 'banlist character',
 'banlist ip',
 'character customize',
 'character level',
 'character reputation',
 'character titles',
 'event',
 'event activelist',
 'event start',
 'event stop',
 'explorecheat',
 'gobject',
 'gobject activate',
 'gobject move',
 'gobject set phase',
 'gobject turn',
 'honor',
 'hover',
 'instance',
 'instance listbinds',
 'instance stats',
 'instance unbind',
 'learn',
 'list auras',
 'lookup event',
 'lookup player account',
 'lookup player email',
 'lookup player ip',
 'lookup taxinode',
 'maxskill',
 'modify money',
 'modify rep',
 'modify standstate',
 'npc delete',
 'npc set level',
 'npc set spawntime',
 'pet',
 'pet unlearn',
 'playall',
 'quest add',
 'repairitems',
 'respawn',
 'send mail',
 'setskill',
 'ticket assign',
 'titles add',
 'titles current',
 'titles remove',
 'titles set mask',
 'unban',
 'unban account',
 'unban ip');
UPDATE `command` SET `security` = 4 WHERE `name` IN (
 'additem',
 'cooldown',
 'gobject add temp',
 'gobject info',
 'gobject near',
 'gobject target',
 'levelup',
 'list',
 'lookup faction',
 'lookup item',
 'lookup itemset',
 'lookup quest',
 'lookup skill',
 'lookup spell',
 'lookup title',
 'modify energy',
 'modify honor',
 'modify phase',
 'npc add temp',
 'quest',
 'quest complete',
 'quest remove',
 'reset',
 'reset talents',
 'tele group',
 'unaura',
 'unlearn',
 'wp add',
 'wp event',
 'wp load',
 'wp show',
 'wp unload');
UPDATE `command` SET `security` = 3 WHERE `name` IN (
 'account password',
 'achievement status',
 'appear',
 'baninfo',
 'baninfo account',
 'baninfo character',
 'baninfo ip',
 'combatstop',
 'demorph',
 'die',
 'freeze',
 'gm',
 'gm chat',
 'gm fly',
 'gm visible',
 'go',
 'go creature',
 'go graveyard',
 'go grid',
 'go object',
 'go taxinode',
 'go ticket',
 'go trigger',
 'go xyz',
 'gps',
 'groupsummon',
 'guid',
 'kick',
 'listfreeze',
 'lookup',
 'lookup tele',
 'modify',
 'modify aspeed',
 'modify bwalk',
 'modify drunk',
 'modify fly',
 'modify hp',
 'modify mana',
 'modify morph',
 'modify mount',
 'modify rage',
 'modify runicpower',
 'modify scale',
 'modify speed',
 'modify swim',
 'npc',
 'npc info',
 'npc playemote',
 'npc say',
 'npc textemote',
 'npc whisper',
 'npc yell',
 'pinfo',
 'recall',
 'revive',
 'save',
 'server info',
 'summon',
 'taxicheat',
 'tele',
 'tele name',
 'ticket',
 'ticket close',
 'ticket closedlist',
 'ticket comment',
 'ticket list',
 'ticket onlinelist',
 'ticket unassign',
 'ticket viewid',
 'ticket viewname',
 'unfreeze',
 'waterwalk',
 'whispers',
 'wpgps');
UPDATE `command` SET `security` = 2 WHERE `name` IN (
 'announce',
 'gmannounce',
 'gmnameannounce',
 'gmnotify',
 'nameannounce',
 'notify');
UPDATE `command` SET `security` = 1 WHERE `name` IN (
 'commands',
 'gm ingame',
 'help',
 'mute',
 'server motd',
 'start',
 'unmute');
UPDATE `command` SET `security` = 0 WHERE `name` IN ('account','account lock','dismount');

-- A more informative mute system
REPLACE INTO `trinity_string` VALUES ('357', 'Player %s is muted for %u minutes. Reason: %s.', null, null, null, null, null, null, null, 'Игроку %s отключен чат на %u минут. Причина: %s.');
REPLACE INTO `trinity_string` VALUES ('358', '%s mutes player %s for %u minutes. Reason: %s.', null, null, null, null, null, null, null, '%s отключает чат игроку %s на %u минут. Причина: %s.');
REPLACE INTO `trinity_string` VALUES ('359', 'Player %s is unmuted now.', null, null, null, null, null, null, null, 'Игрок %s снова может писать сообщения в чат.');
REPLACE INTO `trinity_string` VALUES ('360', '%s unmutes player %s.', null, null, null, null, null, null, null, '%s разрешает игроку %s писать сообщения в чат.');
REPLACE INTO `trinity_string` VALUES ('300', 'Your chat has been disabled by %s for %u minutes. Reason: %s.', null, null, null, null, null, null, null, 'Чат отключен (%s) на %u минут. Причина: %s.');
REPLACE INTO `trinity_string` VALUES ('303', 'Your chat has been enabled by %s.', null, null, null, null, null, null, null, 'Чат снова включен %s.');

-- .nameannounce for differrent GM ranks
REPLACE INTO `trinity_string` VALUES ('787', '|cffffff00[|c1fE82FE8Moderator|cffffff00]|r %s|cffffff00:|r %s|r', null, null, null, null, null, null, null, '|cffffff00[|c1fE82FE8Модератор|cffffff00]|r %s|cffffff00:|r %s|r');
REPLACE INTO `trinity_string` VALUES ('788', '|cffffff00[|c1f0FF20FGM|cffffff00]|r %s|cffffff00:|r %s|r', null, null, null, null, null, null, null, '|cffffff00[|c1f0FF20FГМ|cffffff00]|r %s|cffffff00:|r %s|r');
REPLACE INTO `trinity_string` VALUES ('789', '|cffffff00[|c1f40af20Admin|cffffff00]|r %s|cffffff00:|r %s|r', null, null, null, null, null, null, null, '|cffffff00[|c1f40af20Администратор|cffffff00]|r %s|cffffff00:|r %s|r');

-- .ban/unban character
REPLACE INTO `command` VALUES ('ban character','5','Syntax: .ban character $Name $bantime $reason\n\rBan character and kick player.\n\r$bantime: negative value leads to permban\, otherwise use a timestring like "4d20h3s".');
REPLACE INTO `command` VALUES ('unban character','5','Syntax: .unban character $Name\n\rUnban accounts for character name pattern.' );

-- .server set
REPLACE INTO `command` VALUES ('server set difftime','6','Syntax: .server set difftime $timeMS\n\rSets server log update interval to $timeMS');
#REPLACE INTO `command` VALUES ('server set loglevel','8','Syntax: .server set loglevel #level\n\rSet server log level (0 - errors only\, 1 - basic\, 2 - detail\, 3 - debug).');
#REPLACE INTO `command` VALUES ('server set logfilelevel','8','Syntax: .server set logfilelevel #level\n\rSet server log level (0 - errors only\, 1 - basic\, 2 - detail\, 3 - debug).');
REPLACE INTO `command` VALUES ('server set motd','6','Syntax: .server set motd $MOTD\n\rSet server Message of the day.');
REPLACE INTO `command` VALUES ('server plimit','7','Syntax: .server plimit [#num|-1|-2|-3|reset|player|moderator|gamemaster|administrator]\n\rWithout arg shows current player amount and security level limitations for login to server.\n\rWith arg sets the player limit ($num > 0) or security limitation ($num < 0 or security level name).\n\rWith `reset` reloads player limit from the config file.');
